# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

#-------------------------------
# General Site Settings
title: Matt Lindsay
subtitle: Senior Software Engineer
email: melittlematt@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My name is Matt, and I'm a Senior Software Engineer living in Norfolk, UK.
  This is my personal bio, portfolio, CV and blog website! Please feel free
  to get in contact if you would like to collaborate together.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mattlindsay.dev" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: melittlematt
github_username:  melittleman
author: Matthew Lindsay
county: Norfolk
country: United Kingdom

#-------------------------------
# Collections
collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  projects:
    output: true
    permalink: /project/:slug

#-------------------------------
# Page Settings
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

paginate: 6
paginate_path: "/blog/page/:num"

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 1

#-------------------------------
# Social Settings (key must match name of font awesome icon)
# see: https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/melittleman
  LinkedIn: https://www.linkedin.com/in/mattlindsay94
  Twitter: https://twitter.com/melittlematt
  Instagram: https://www.instagram.com/mattylindsay_
  Discord: https://discordapp.com/users/544209764486479882

#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-feed
  - jekyll-timeago
  - jekyll-paginate
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
exclude:
- "*.gemspec"
- LICENSE
- README.md 
- .sass-cache/
- .jekyll-cache/
- gemfiles/
- Gemfile
- Gemfile.lock
- node_modules/
